export const GET_USER_REQUEST = "GET_USER_REQUEST"; 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"; 
export const GET_USER_FAIL = "GET_USER_FAIL"; 

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST"; 
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"; 
export const EDIT_USER_FAIL = "EDIT_USER_FAIL"; 