export const GET_USER_REQUEST = "GET_USER_REQUEST"; 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"; 
export const GET_USER_FAIL = "GET_USER_FAIL"; 

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"; 
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"; 
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"; 

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST"; 
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"; 
export const EDIT_USER_FAIL = "EDIT_USER_FAIL"; 

export const EDIT_STATUS_USER_REQUEST = "EDIT_STATUS_USER_REQUEST"; 
export const EDIT_STATUS_USER_SUCCESS = "EDIT_STATUS_USER_SUCCESS"; 
export const EDIT_STATUS_USER_FAIL = "EDIT_STATUS_USER_FAIL";

export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST"; 
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS"; 
export const APPROVE_USER_FAIL = "APPROVE_USER_FAIL"; 

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"; 
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"; 
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"; 