export const GET_ALL_BOARD_REQUEST = "GET_ALL_BOARD_REQUEST";
export const GET_ALL_BOARD_SUCCESS = "GET_ALL_BOARD_SUCCESS";
export const GET_ALL_BOARD_FAIL = "GET_ALL_BOARD_FAIL";

export const GET_BOARD_REQUEST = "GET_BOARD_REQUEST";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_FAIL = "GET_BOARD_FAIL";

export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAIL = "CREATE_BOARD_FAIL";

export const ACTION_BOARD_REQUEST = "ACTION_BOARD_REQUEST";
export const ACTION_BOARD_SUCCESS = "ACTION_BOARD_SUCCESS";
export const ACTION_BOARD_FAIL = "ACTION_BOARD_FAIL";

export const EDIT_BOARD_REQUEST = "EDIT_BOARD_REQUEST";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_FAIL = "EDIT_BOARD_FAIL";

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL";

export const HISTORY_BOARD_LIST_REQUEST = "HISTORY_BOARD_LIST_REQUEST";
export const HISTORY_BOARD_LIST_SUCCESS = "HISTORY_BOARD_LIST_SUCCESS";
export const HISTORY_BOARD_LIST_FAIL = "HISTORY_BOARD_LIST_FAIL";

export const RESTORE_HISTORY_BOARD_REQUEST = "RESTORE_HISTORY_BOARD_REQUEST";
export const RESTORE_HISTORY_BOARD_SUCCESS = "RESTORE_HISTORY_BOARD_SUCCESS";
export const RESTORE_HISTORY_BOARD_FAIL = "RESTORE_HISTORY_BOARD_FAIL";

export const CHECK_BOARD_REQUEST = "CHECK_BOARD_REQUEST";
export const CHECK_BOARD_SUCCESS = "CHECK_BOARD_SUCCESS";
export const CHECK_BOARD_FAIL = "CHECK_BOARD_FAIL";

export const INCOMPLETE_TOOL_REQUEST = "INCOMPLETE_TOOL_REQUEST";
export const INCOMPLETE_TOOL_SUCCESS = "INCOMPLETE_TOOL_SUCCESS";
export const INCOMPLETE_TOOL_FAIL = "INCOMPLETE_TOOL_FAIL";

export const EDIT_INCOMPLETE_TOOL_REQUEST = "EDIT_INCOMPLETE_TOOL_REQUEST";
export const EDIT_INCOMPLETE_TOOL_SUCCESS = "EDIT_INCOMPLETE_TOOL_SUCCESS";
export const EDIT_INCOMPLETE_TOOL_FAIL = "EDIT_INCOMPLETE_TOOL_FAIL";

export const DELETE_INCOMPLETE_TOOL_REQUEST = "DELETE_INCOMPLETE_TOOL_REQUEST";
export const DELETE_INCOMPLETE_TOOL_SUCCESS = "DELETE_INCOMPLETE_TOOL_SUCCESS";
export const DELETE_INCOMPLETE_TOOL_FAIL = "DELETE_INCOMPLETE_TOOL_FAIL";

