export const GET_ALL_BOARD_REQUEST = "GET_ALL_BOARD_REQUEST";
export const GET_ALL_BOARD_SUCCESS = "GET_ALL_BOARD_SUCCESS";
export const GET_ALL_BOARD_FAIL = "GET_ALL_BOARD_FAIL";

export const GET_BOARD_REQUEST = "GET_BOARD_REQUEST";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_FAIL = "GET_BOARD_FAIL";

export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAIL = "CREATE_BOARD_FAIL";

export const ACTION_BOARD_REQUEST = "ACTION_BOARD_REQUEST";
export const ACTION_BOARD_SUCCESS = "ACTION_BOARD_SUCCESS";
export const ACTION_BOARD_FAIL = "ACTION_BOARD_FAIL";

export const EDIT_BOARD_REQUEST = "EDIT_BOARD_REQUEST";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_FAIL = "EDIT_BOARD_FAIL";

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL";