// export const GET_USER_REQUEST = "GET_USER_REQUEST"; 
// export const GET_USER_SUCCESS = "GET_USER_SUCCESS"; 
// export const GET_USER_FAIL = "GET_USER_FAIL"; 

export const GET_ALL_TYPE_REQUEST = "GET_ALL_TYPE_REQUEST"; 
export const GET_ALL_TYPE_SUCCESS = "GET_ALL_TYPE_SUCCESS"; 
export const GET_ALL_TYPE_FAIL = "GET_ALL_TYPE_FAIL"; 

export const ADD_TYPE_REQUEST = "ADD_TYPE_REQUEST"; 
export const ADD_TYPE_SUCCESS = "ADD_TYPE_SUCCESS"; 
export const ADD_TYPE_FAIL = "ADD_TYPE_FAIL"; 

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST"; 
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"; 
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const EDIT_TYPE_REQUEST = "EDIT_TYPE_REQUEST"; 
export const EDIT_TYPE_SUCCESS = "EDIT_TYPE_SUCCESS"; 
export const EDIT_TYPE_FAIL = "EDIT_TYPE_FAIL"; 

export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST"; 
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS"; 
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL"; 

// export const EDIT_STATUS_USER_REQUEST = "EDIT_STATUS_USER_REQUEST"; 
// export const EDIT_STATUS_USER_SUCCESS = "EDIT_STATUS_USER_SUCCESS"; 
// export const EDIT_STATUS_USER_FAIL = "EDIT_STATUS_USER_FAIL";

// export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST"; 
// export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS"; 
// export const APPROVE_USER_FAIL = "APPROVE_USER_FAIL"; 

export const DELETE_TYPE_REQUEST = "DELETE_TYPE_REQUEST"; 
export const DELETE_TYPE_SUCCESS = "DELETE_TYPE_SUCCESS"; 
export const DELETE_TYPE_FAIL = "DELETE_TYPE_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST"; 
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"; 
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL"; 