export const GET_ALL_TOOL_REQUEST = "GET_ALL_TOOL_REQUEST";
export const GET_ALL_TOOL_SUCCESS = "GET_ALL_TOOL_SUCCESS";
export const GET_ALL_TOOL_FAIL = "GET_ALL_TOOL_FAIL";

export const CREATE_TOOL_REQUEST = "CREATE_TOOL_REQUEST";
export const CREATE_TOOL_SUCCESS = "CREATE_TOOL_SUCCESS";
export const CREATE_TOOL_FAIL = "CREATE_TOOL_FAIL";

export const ACTION_TOOL_REQUEST = "ACTION_TOOL_REQUEST";
export const ACTION_TOOL_SUCCESS = "ACTION_TOOL_SUCCESS";
export const ACTION_TOOL_FAIL = "ACTION_TOOL_FAIL";